name: Custom Notifications
on:
  issues:
    types: [opened, edited, deleted, closed]
  issue_comment:
    types: [created]
  workflow_run:
    workflows: ["Release"]
    types: [completed]
  pull_request_target:
    types: [opened, closed, edited, review_requested]

jobs:
  issue-comment-notification:
    if: github.event_name == 'issues' || github.event_name == 'issue_comment'
    runs-on: ubuntu-latest
    steps:
      - name: Notify on Issue or Comment
        if: github.actor != 'Tanq16'
        run: |
          curl -H "Content-Type: application/json" -X POST \
          -d "{\"content\": \"*New issue/comment from **${{ github.actor }}***\n${{ github.event.issue.html_url }}\"}" ${{ secrets.DISCORD_WEBHOOK }}

  build-status-notification:
    if: github.event_name == 'workflow_run'
    runs-on: ubuntu-latest
    steps:
      - name: Notify on Build Status
        run: |
          if [ "${{ github.event.workflow_run.conclusion }}" = "success" ]; then
            EMOJI="‚úÖ"
          else
            EMOJI="‚ùå"
          fi
          curl -H "Content-Type: application/json" -X POST \
          -d "{\"content\": \"${EMOJI} *Workflow run for **${{ github.repository }}***\n${{ github.event.workflow_run.name }} - ${{ github.event.workflow_run.conclusion }}\"}" ${{ secrets.DISCORD_WEBHOOK }}

  pull-request-notification:
    if: github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    steps:
      - name: Notify on PR related activities
        if: github.actor != 'Tanq16'
        run: |
          ACTION="${{ github.event.action }}"
          if [ "$ACTION" = "opened" ]; then
            EMOJI="üÜï"
            MSG="opened"
          elif [ "$ACTION" = "closed" ] && [ "${{ github.event.pull_request.merged }}" = "true" ]; then
            EMOJI="üéâ"
            MSG="merged"
          elif [ "$ACTION" = "closed" ]; then
            EMOJI="üö´"
            MSG="closed"
          elif [ "$ACTION" = "review_requested" ]; then
            EMOJI="üëÄ"
            MSG="review requested"
          else
            EMOJI="üìù"
            MSG="$ACTION"
          fi
          curl -H "Content-Type: application/json" -X POST \
          -d "{\"content\": \"${EMOJI} *PR ${MSG} by **${{ github.actor }}***\n${{ github.event.pull_request.html_url }}\"}" ${{ secrets.DISCORD_WEBHOOK }}
